spring.application.name=sb-ecom

#POSTGRES DATASOURCE Configuration:
spring.datasource.url = jdbc:postgresql://localhost:5432/db_ecommerce
spring.datasource.username = postgres
spring.datasource.password = Syed@123

#HIBERNATE-JPA Configuration
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#Path for images
#use of @Value("${project.images}")
project.images=images/

spring.app.jwtSecretKey=dffrwerwf2313ddfdmkmoimpotkeoconrjoiej43434343infsfgcxv
spring.app.jwtExpirationMs=3000000


#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG

#>> Whole Project Wise Log -> DEBUG Level
#logging.level.com.ecommerce.project=DEBUG


# >> H2 Database configuration << #
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#jdbc(protocol) :h2(db) :mem(Ram memory): urlPath
#jdbc(protocol) :h2(db) :file(SecondaryMemory): path



#MYSQL DATASOURCE Configuration:
#spring.datasource.url = jdbc:mysql://localhost:3306/db_ecommerce
#spring.datasource.username = root
#spring.datasource.password = Syed@123
#
#HIBERNATE-JPA Configuration
#spring.jpa.show-sql = true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect