spring.application.name=sb-ecom

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
#jdbc(protocol) :h2(db) :mem(Ram memory): urlPath
#jdbc(protocol) :h2(db) :file(SecondaryMemory): path

spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto= update
#update: (update the table or entity if already exists)
#create: drop the previous entity if exist and create new
#create-drop: create when App. start and drop when App. terminates.

#Path for images
#use of @Value("${project.images}")
project.images=images/


spring.app.jwtSecretKey=dffrwerwf2313ddfdmkmoimpotkeoconrjoiej43434343infsfgcxv
spring.app.jwtExpirationMs=3000000


#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#
##Whole Project Wise Log -> DEBUG Level
#logging.level.com.ecommerce.project=DEBUG